[package]
name = "assignment_1"
version = "0.1.0"
authors = ["moa93w <moa93w@umsystem.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5"
linked_hash_set = "0.1.4"
linked-hash-map = "0.5.4"
